USE [DB_NAME]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Mottu_Table_Couriers] (
    Id INT IDENTITY(1,1),
    Identifier NVARCHAR(50) NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    CNPJ NVARCHAR(14) NOT NULL UNIQUE,
    BirthDate DATE NOT NULL,
    CNHNumber NVARCHAR(20) NOT NULL UNIQUE,
    CNHType NVARCHAR(3) NOT NULL CHECK (CNHType IN ('A', 'B', 'A+B')),
    CNHImagePath NVARCHAR(255) NULL,
    RegistrationDate DATETIME DEFAULT GETDATE(),
 CONSTRAINT [PK_Table_Couriers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



