CREATE TABLE Couriers (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Identifier NVARCHAR(50) NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    CNPJ NVARCHAR(14) NOT NULL UNIQUE,
    BirthDate DATE NOT NULL,
    CNHNumber NVARCHAR(20) NOT NULL UNIQUE,
    CNHType NVARCHAR(3) NOT NULL CHECK (CNHType IN ('A', 'B', 'A+B')),
    CNHImagePath NVARCHAR(255) NULL,
    RegistrationDate DATETIME DEFAULT GETDATE()
);
