CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Username NVARCHAR(50) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    ProfileId INT NOT NULL FOREIGN KEY REFERENCES UserProfiles(Id),
    CreatedAt DATETIME DEFAULT GETDATE()
);
